// app/components/organisms/HeroSection.vue
<template>
  <section ref="heroRef" class="relative flex min-h-dvh w-full items-center justify-center overflow-hidden">
    <!-- Background -->
    <div class="absolute inset-0 z-0">
      <img src="/images/hero-bg.webp" alt="" class="h-full w-full object-cover object-[center_30%]" loading="eager" />
      <div class="absolute inset-x-0 top-0 h-[30%] bg-gradient-to-b from-[rgba(10,10,15,0.8)] to-transparent" />
      <div class="absolute inset-x-0 bottom-0 h-[40%] bg-gradient-to-t from-surface-primary to-transparent" />
    </div>

    <!-- Particles -->
    <div
      class="pointer-events-none absolute inset-0 z-[1] animate-[particle-drift_20s_linear_infinite]"
      style="background-image: radial-gradient(1px 1px at 20% 30%, rgba(255,255,255,0.3), transparent), radial-gradient(1px 1px at 60% 70%, rgba(212,168,67,0.2), transparent), radial-gradient(1px 1px at 80% 20%, rgba(255,255,255,0.2), transparent)"
    />

    <!-- Content -->
    <div
      ref="contentRef"
      class="relative z-[2] flex flex-col items-center gap-6 px-6 text-center"
      v-motion
      :initial="{ opacity: 0, y: 40 }"
      :enter="{ opacity: 1, y: 0, transition: { duration: 1200, ease: 'easeOut' } }"
    >
      <div ref="logoRef" class="w-[clamp(200px,40vw,400px)]">
        <img :src="'/images/logo.webp'" :alt="SITE.name" class="w-full drop-shadow-[0_0_40px_rgba(212,168,67,0.3)]" />
      </div>

      <h1 class="max-w-[600px] font-display text-[clamp(1rem,2.5vw,1.5rem)] font-normal uppercase tracking-[0.15em] text-white/60">
        {{ t('hero.tagline') }}
      </h1>

      <div class="mt-4">
        <NuxtLink
          to="/event"
          class="group relative inline-flex h-[52px] items-center justify-center overflow-hidden rounded-full bg-gradient-to-br from-gold to-gold-light px-10 text-[0.9375rem] font-extrabold uppercase tracking-wider text-black shadow-[0_0_30px_rgba(212,168,67,0.3)] transition-all duration-500 hover:-translate-y-0.5 hover:shadow-[0_0_50px_rgba(212,168,67,0.5)]"
        >
          <span class="relative z-[1]">{{ t('hero.cta') }}</span>
          <span class="absolute inset-0 -left-full animate-[glow-sweep_3s_ease-in-out_infinite] bg-gradient-to-r from-transparent via-white/30 to-transparent" />
        </NuxtLink>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { SITE } from '~/shared/constants'
const { t } = useI18n()
</script>

// src/components/sections/HeroSection.tsx
'use client';

import { useLang } from '@/lib/lang-context';
import Image from 'next/image';
import { motion } from 'framer-motion';

export default function HeroSection({ data }: { data: any }) {
  const { currentLang } = useLang();
  
  if (!data) return null;

  const tagline = currentLang === 'en' ? data.taglineEn : data.taglineTh;
  const ctaText = currentLang === 'en' ? data.ctaTextEn : data.ctaTextTh;
  const bgImageUrl = typeof data.backgroundImage === 'object' ? data.backgroundImage.url : data.backgroundImage;

  return (
    <section className="relative w-full h-[85vh] min-h-[600px] flex items-center justify-center overflow-hidden">
      {/* Background Media */}
      <div className="absolute inset-0 z-0">
        {bgImageUrl && (
          <Image 
            src={bgImageUrl} 
            alt="Hero Background" 
            fill 
            className="object-cover object-top opacity-70"
            priority
          />
        )}
        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/40 to-transparent" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-transparent to-black/80" />
      </div>

      {/* Content */}
      <div className="relative z-10 text-center px-6 max-w-4xl mx-auto flex flex-col items-center">
        <motion.h1 
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="text-4xl md:text-6xl lg:text-7xl font-black uppercase tracking-tight text-white drop-shadow-[0_0_20px_rgba(0,0,0,0.8)]"
        >
          {tagline}
        </motion.h1>
        
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5, duration: 1 }}
          className="mt-10"
        >
          <a 
            href={data.ctaLink || '#'}
            className="group relative inline-flex items-center justify-center px-8 py-4 bg-white text-black font-bold text-lg uppercase tracking-widest overflow-hidden transition-transform hover:scale-105 active:scale-95"
          >
            <span className="relative z-10">{ctaText}</span>
            <div className="absolute inset-0 bg-gradient-to-r from-gray-200 to-white opacity-0 group-hover:opacity-100 transition-opacity" />
          </a>
        </motion.div>
      </div>
    </section>
  );
}
