// src/components/sections/NewsSection.tsx
'use client';

import { useLang } from '@/lib/lang-context';
import { motion } from 'framer-motion';
import Link from 'next/link';
import type { CMSNewsArticle } from '@/types/cms';

export default function NewsSection({ data, news }: { data: any, news: CMSNewsArticle[] }) {
  const { lang: currentLang } = useLang();
  
  if (!data) return null;

  const title = currentLang === 'en' ? data.titleEn : data.titleTh;
  const displayNews = news?.length ? news : [
    { id: '1', slug: 'patch-1', titleEn: 'Patch 1.0.4 Update', category: 'Update', publishedAt: '2026-04-01' },
    { id: '2', slug: 'event-1', titleEn: 'Spring Festival Event', category: 'Event', publishedAt: '2026-03-28' },
    { id: '3', slug: 'notice-1', titleEn: 'Server Maintenance', category: 'Notice', publishedAt: '2026-03-25' },
  ] as any[];

  return (
    <section 
      className="relative w-full min-h-[100svh] py-24 flex flex-col justify-center items-center overflow-hidden bg-zinc-950" 
      id="news"
    >
      <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-indigo-900/10 to-transparent pointer-events-none z-0" />

      <div className="container mx-auto px-6 max-w-7xl flex flex-col md:flex-row gap-8 lg:gap-16 items-center relative z-10 py-20 h-full">
        <div className="md:w-1/3 flex flex-col justify-center">
          <motion.h2 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl lg:text-6xl font-black text-white uppercase tracking-widest mb-6 drop-shadow-lg"
          >
            {title}
          </motion.h2>
          <motion.div 
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
          >
            <Link 
              href="/news" 
              className="inline-flex items-center gap-2 text-indigo-400 hover:text-white font-bold uppercase tracking-wider text-sm transition-colors group"
            >
              View All News 
              <span className="group-hover:translate-x-2 transition-transform">ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢</span>
            </Link>
          </motion.div>
        </div>

        <div className="md:w-2/3 flex flex-col gap-3 md:gap-4 w-full max-w-2xl">
          {displayNews.slice(0, 3).map((item, idx) => {
            const itemTitle = currentLang === 'en' ? (item.titleEn || item.title) : (item.titleTh || item.title);
            const date = new Date(item.publishedAt).toLocaleDateString(currentLang === 'en' ? 'en-US' : 'th-TH', {
              year: 'numeric', month: 'short', day: 'numeric'
            });

            return (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Link 
                  href={`/news/${item.slug}`}
                  className="group flex flex-col sm:flex-row sm:items-center justify-between p-5 md:p-6 bg-black/60 backdrop-blur-sm border border-white/10 hover:border-indigo-500/50 rounded-xl transition-all hover:bg-zinc-900/80"
                >
                  <div className="flex flex-col sm:flex-row sm:items-center gap-3 md:gap-4">
                    <span className="px-3 py-1 bg-white/5 text-gray-300 group-hover:text-white group-hover:bg-indigo-500/20 text-xs font-bold uppercase tracking-wider rounded-sm w-fit transition-colors">
                      {item.category || 'News'}
                    </span>
                    <h3 className="text-base md:text-lg font-bold text-gray-300 group-hover:text-white transition-colors line-clamp-1">
                      {itemTitle}
                    </h3>
                  </div>
                  <span className="text-gray-500 text-xs md:text-sm mt-3 sm:mt-0 whitespace-nowrap font-mono">
                    {date}
                  </span>
                </Link>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// app/components/organisms/NewsSection.vue
<template>
  <section
    id="news"
    class="relative overflow-hidden bg-bg-1 py-32"
    data-screen-label="06 News"
  >
    <div class="pointer-events-none absolute inset-x-0 top-0 h-32 bg-gradient-to-b from-bg-0 to-transparent" />
    <div class="pointer-events-none absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-bg-0 to-transparent" />

    <div class="relative mx-auto max-w-7xl px-6">
      <!-- ── Header ─────────────────────────────────── -->
      <header
        class="mb-16 flex flex-wrap items-end justify-between gap-6"
        v-motion
        :initial="{ opacity: 0, y: 24 }"
        :visible-once="{ opacity: 1, y: 0, transition: { duration: 800 } }"
      >
        <div class="flex flex-col gap-4">
          <div class="section-eyebrow">
            <span><span class="num">06</span>&nbsp;&nbsp;LATEST&nbsp;UPDATES</span>
            <span class="h-px w-12 bg-gradient-to-r from-gold/60 to-transparent" />
          </div>
          <h2 class="section-title">{{ t('news.title') }}</h2>
        </div>
        <NuxtLink
          to="/news"
          class="group inline-flex items-center gap-3 font-mono text-[11px] font-semibold uppercase tracking-[0.25em] text-gold no-underline transition-all duration-300 hover:gap-5"
        >
          {{ t('news.viewAll') }}
          <span class="block h-px w-10 bg-gold transition-all duration-300 group-hover:w-16" />
          <svg class="h-3 w-3 transition-transform duration-300 group-hover:rotate-[-45deg]" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 10 L10 2 M5 2 L10 2 L10 7" /></svg>
        </NuxtLink>
      </header>

      <!-- ── Asymmetric grid: 1 feature + 2 small ─── -->
      <div class="grid grid-cols-1 gap-6 lg:grid-cols-[1.4fr_1fr] lg:gap-8">
        <!-- ▼ Featured (left, large) -->
        <NuxtLink
          v-if="featuredArticle"
          :to="featuredArticle.href"
          class="group relative overflow-hidden rounded-[2px] border border-ink/8 bg-bg-2 no-underline transition-all duration-500 hover:border-gold/40"
          style="min-height: clamp(380px, 44vw, 560px);"
          v-motion
          :initial="{ opacity: 0, y: 32 }"
          :visible-once="{ opacity: 1, y: 0, transition: { duration: 800, delay: 100 } }"
        >
          <img
            :src="featuredArticle.image"
            :alt="localizedTitle(featuredArticle)"
            class="absolute inset-0 h-full w-full object-cover transition-transform duration-[900ms] group-hover:scale-[1.04]"
            loading="lazy"
          />
          <div class="absolute inset-0 bg-gradient-to-t from-bg-0 via-bg-0/50 to-transparent" />
          <div class="cinematic-corners absolute inset-5" />

          <span
            class="absolute left-6 top-6 inline-flex items-center gap-2 rounded-full border border-gold/40 bg-bg-0/70 px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.3em] text-gold backdrop-blur-md"
          >
            <span class="h-1 w-1 rounded-full bg-gold-bright" />
            {{ t('news.featured') }}
          </span>

          <div class="absolute inset-x-0 bottom-0 flex flex-col gap-4 p-8 md:p-10">
            <div class="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.3em] text-ink-mute">
              <span class="text-gold-bright">{{ formatDate(featuredArticle.date) }}</span>
              <span class="h-px flex-1 max-w-[60px] bg-ink/20" />
              <span>{{ localizedCategory(featuredArticle) }}</span>
            </div>
            <h3 class="font-display text-[clamp(1.5rem,2.8vw,2.25rem)] font-bold leading-tight text-ink transition-colors duration-300 group-hover:text-gold-bright">
              {{ localizedTitle(featuredArticle) }}
            </h3>
            <p
              v-if="localizedExcerpt(featuredArticle)"
              class="line-clamp-2 max-w-[60ch] text-sm leading-relaxed text-ink-soft"
            >
              {{ localizedExcerpt(featuredArticle) }}
            </p>
            <div class="mt-2 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.3em] text-gold opacity-80 transition-all duration-300 group-hover:gap-5 group-hover:opacity-100">
              <span>{{ t('news.readMore') }}</span>
              <span class="block h-px w-8 bg-gold transition-all duration-300 group-hover:w-12" />
            </div>
          </div>
        </NuxtLink>

        <!-- ▼ Small column (right, 2 stacked) -->
        <div class="flex flex-col gap-6">
          <NuxtLink
            v-for="(article, idx) in smallArticles"
            :key="article.id"
            :to="article.href"
            class="group relative flex-1 overflow-hidden rounded-[2px] border border-ink/8 bg-bg-2 no-underline transition-all duration-500 hover:border-gold/40"
            style="min-height: clamp(180px, 22vw, 270px);"
            v-motion
            :initial="{ opacity: 0, y: 32 }"
            :visible-once="{ opacity: 1, y: 0, transition: { duration: 700, delay: 200 + idx * 120 } }"
          >
            <img
              :src="article.image"
              :alt="localizedTitle(article)"
              class="absolute inset-0 h-full w-full object-cover transition-transform duration-[900ms] group-hover:scale-[1.06]"
              loading="lazy"
            />
            <div class="absolute inset-0 bg-gradient-to-t from-bg-0 via-bg-0/55 to-transparent" />

            <div class="absolute inset-x-0 bottom-0 flex flex-col gap-2 p-6">
              <div class="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.3em] text-ink-mute">
                <span class="text-gold-bright">{{ formatDate(article.date) }}</span>
                <span class="h-px w-6 bg-ink/20" />
                <span>{{ localizedCategory(article) }}</span>
              </div>
              <h3 class="line-clamp-2 font-display text-lg font-bold leading-tight text-ink transition-colors duration-300 group-hover:text-gold-bright">
                {{ localizedTitle(article) }}
              </h3>
            </div>
          </NuxtLink>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
interface NewsArticle {
  id: string
  titleEn: string
  titleTh: string
  excerptEn?: string
  excerptTh?: string
  categoryEn?: string
  categoryTh?: string
  image: string
  date: string | Date
  href: string
  featured?: boolean
}

const props = defineProps<{
  articles: NewsArticle[]
}>()

const { t, locale } = useI18n()

// Pick the first featured (or first overall) for the big slot, next 2 for the column
const featuredArticle = computed<NewsArticle | undefined>(() => {
  return props.articles.find((a) => a.featured) || props.articles[0]
})
const smallArticles = computed<NewsArticle[]>(() => {
  const featured = featuredArticle.value
  return props.articles.filter((a) => a !== featured).slice(0, 2)
})

function localizedTitle(a: NewsArticle) { return locale.value === 'th' ? (a.titleTh || a.titleEn) : (a.titleEn || a.titleTh) }
function localizedExcerpt(a: NewsArticle) { return locale.value === 'th' ? (a.excerptTh || a.excerptEn || '') : (a.excerptEn || a.excerptTh || '') }
function localizedCategory(a: NewsArticle) { return locale.value === 'th' ? (a.categoryTh || a.categoryEn || '') : (a.categoryEn || a.categoryTh || '') }

function formatDate(d: string | Date) {
  const date = typeof d === 'string' ? new Date(d) : d
  if (isNaN(date.getTime())) return ''
  const fmt = new Intl.DateTimeFormat(locale.value === 'th' ? 'th-TH' : 'en-US', {
    day: '2-digit', month: 'short', year: 'numeric',
  })
  return fmt.format(date).toUpperCase()
}
</script>
